spring:
  datasource:
    url: jdbc:mysql://192.168.1.207:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1
logging:
  level:
    root: info
