spring:
  datasource:
    url: jdbc:mysql://192.168.2.201:33306/mysql
    username: dldp_dev
    password: dldp@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1
logging:
  level:
    root: info
